spring.application.name=kenshu2app

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kenshudb
spring.datasource.username=postgres
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

spring.thymeleaf.cache=false